### ISSUE TITLE
Issues with Windows builds

### ISSUE THREAD

**Issue by ralphlange** [epics-base/bundleCPP#1]
From W. Todd Sneed <todd.sneed _AT_ nhancetech.com>:

Building 4.5.0.2 on different Windows variants:
[...]
Next, I tried to build Epics 4.5.  There are several different permutations we've tried, but what I think is going on is there some sort of incompatibility between the perl/make scripts and the linker.  Specifically, if I want to build the system, I modify the RELEASE.local to have EV4_BASE = c:/epics/EPICS-cpp-4.5.0.2 but if I make EPICS_BASE=c:/epics/base-3.15.4 the perl scripts/make gives me an error.  If I make EPICS_BASE=/epics/base-3.15.4 then the make itself goes through, but when it gets to the point of linking, the linker gives an error because it doesn't recognize a library file that starts with /epics/base-3.15.4/...  I need to use c:/epics/base in the path... I started creating several l.bat files for the projects to get the link to work, but that was tedious, and I discovered if I changed release.local to use EPICS_BASE=../../../../epics/base-3.15.4 or some form of relative path, then the linker will work.  Obviously, the relative path was dependent upon the directory level, so it was a bit cumbersome... and even some projects I had to revert to the l.bat file because of multiple libraries etc. errors.

Then building 4.6.0-pre1:
[...]
To follow up, EPICS 4.6 Pre-1 was much faster to build.  The problem with the perl/make scripts setting the EPICS_BASE was still there, but when the linker generated an error, I could simply CD into the directory (the make script was better output to let me know what directory to go to), and execute a batch file (make4 with 4 ../../../../epics/base-3.15.4 as the relative path)...This put the correct line on the link command, and when that project built, I could run make from base EPICS folder to go to the next error.

**Comment by ralphlange** [comment]
Todd's email: todd.sneed _AT_ nhancetech.com

**Comment by anjohnson** [comment]
Hi Todd,

Ralph Lange forwarded some problems that you're having to a github issue
shown below. I haven't seen anything that you might have written before
the message text below, but I do think you need to fix any Base build
problems first before trying to build EPICS V4.

I'm responsible for the 4.6.0-pre1 version of the EPICS-CPP bundle but
not the 4.5.x bundle, and I also maintain the Base build system. I don't
recognize the problem you're having with the linker, and I wonder
whether your PATH may contain directories with filenames that clash with
Perl or the Visual Studio tools? I currently have Visual Studio 10.0 on
a 64-bit system running Windows 7 and my builds complete without errors,
and other people have reported minor fixes for later versions of Visual
Studio but nothing like you seem to have.

If you look in your Base-3.15.4/startup directory you'll see a win32.bat
file that sets up an environment suitable for building Base. The
contents of this are probably rather old now and will need editing for
your machine anyway, but it shows how we set PATH from scratch when
building Base so as to avoid any other programs that might clash with
those that we rely on. Until you can build Base completely from scratch
with a single 'make' command I don't think you should be trying to build
other modules that depend on it.

If you get stuck of the above doesn't help, please email me, and be sure
to copy & paste the exact text of any errors that you're seeing.

Sorry if you've already been through some of this with Ralph, as I said
all I have to go on at this point is his github issue as quoted below.
- Andrew

On 08/16/2016 09:45 AM, Ralph Lange wrote:

> From W. Todd Sneed :
> 
> Building 4.5.0.2 on different Windows variants:
> [...]
> Next, I tried to build Epics 4.5. There are several different
> permutations we've tried, but what I think is going on is there some
> sort of incompatibility between the perl/make scripts and the linker.
> Specifically, if I want to build the system, I modify the RELEASE.local
> to have EV4_BASE = c:/epics/EPICS-cpp-4.5.0.2 but if I make
> EPICS_BASE=c:/epics/base-3.15.4 the perl scripts/make gives me an error.
> If I make EPICS_BASE=/epics/base-3.15.4 then the make itself goes
> through, but when it gets to the point of linking, the linker gives an
> error because it doesn't recognize a library file that starts with
> /epics/base-3.15.4/... I need to use c:/epics/base in the path... I
> started creating several l.bat files for the projects to get the link to
> work, but that was tedious, and I discovered if I changed release.local
> to use EPICS_BASE=../../../../epics/base-3.15.4 or some form of relative
> path, then the linker will work. Obviously, the relative path was
> dependent upon the directory level, so it was a bit cumbersome... and
> even some projects I had to revert to the l.bat file because of multiple
> libraries etc. errors.
> 
> Then building 4.6.0-pre1:
> [...]
> To follow up, EPICS 4.6 Pre-1 was much faster to build. The problem with
> the perl/make scripts setting the EPICS_BASE was still there, but when
> the linker generated an error, I could simply CD into the directory (the
> make script was better output to let me know what directory to go to),
> and execute a batch file (make4 with 4 ../../../../epics/base-3.15.4 as
> the relative path)...This put the correct line on the link command, and
> when that project built, I could run make from base EPICS folder to go
> to the next error.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/epics-base/bundleCPP/issues/1

## 

Arguing for surveillance because you have nothing to hide is no
different than making the claim, "I don't care about freedom of
speech because I have nothing to say." -- Edward Snowdon

**Comment by anjohnson** [comment]
Hi Andrew,

Thank you for the email.  We have built all or most of the bases with different compilers working on different versions.  For example, 3.15.3 & 3.15.4 work with VS 2015.  Most of 3.14.12.3-3.15.4 build with VS2008 on Windows XP.  When we moved to Windows 10, with Visual Studio 2015, we had trouble with some of the older 3.14 - 3.15.2 versions, but 3.15.3 & 3.15.4 work out of the box with just customizing the batch files and typing make.

We have also tried various different versions and builds using minGW and the GCC compiler.  In this case, most, if not all of the 3.14 and 3.15 versions build.

After all the various iterations, we continued to have issues with building the EPICS 4 versions.  So, to eliminate all of the permutations, I selected the following:

Windows 10
Visual Studio 2015
win32-x86 (I have not tried windows-x64 yet, but would like to after 32-bit is working.).

Now comes the problems.  It is not clear how or what format to set the environment variables EV4_BASE and EPICS_BASE.  For example, I have:

c:\Epics as the root folder, and 
C:\Epics\base-3.15.4
C:\Epics\EPICS-cpp-4.5.0.2
C:\Epics\EPICS-cpp-4.6.0-pre1

The EV4_BASE seems to be fine.  But, how to set EPICS_BASE? eg: c:\epics\base-3.15.4 or c:/epics/base-3.15.4 or /c/epics/base-3.15.4 ?  Non worked 

If I use what I would have considered correct after globbing: c:/epics/base-3.15.4 I get the following:

C:\epics\EPICS-CPP-4.5.0.2>make
make -C pvCommonCPP
Can't open perl script ".": Permission denied
make[1]: Entering directory `C:/epics/EPICS-CPP-4.5.0.2/pvCommonCPP'
make -C ./configure install
Can't open perl script "..": Permission denied
make[2]: Entering directory`C:/epics/EPICS-CPP-4.5.0.2/pvCommonCPP/configure'
make -C O.win32-x86 -f ../Makefile TOP=../.. \
            T_A=win32-x86 install
Can't open perl script "../..": Permission denied
make[3]: Entering directory `C:/epics/EPICS-CPP-4.5.0.2/pvCommonCPP/configure/O.win32-x86'
c:/epics/base-3.15.4/configure/RULES.Db:430: *** multiple target patterns.  Stop.
make[3]: Leaving directory`C:/epics/EPICS-CPP-4.5.0.2/pvCommonCPP/configure/O.win32-x86'
make[2]: **\* [install.win32-x86] Error 2
make[2]: Leaving directory `C:/epics/EPICS-CPP-4.5.0.2/pvCommonCPP/configure'
make[1]: *** [configure.install] Error 2
make[1]: Leaving directory`C:/epics/EPICS-CPP-4.5.0.2/pvCommonCPP'
make: **\* [pvCommon] Error 2

But, if I use EPICS_BASE=/epics/base-3.15.4 (eg. no "c:" ).  Make has no issues with the perl scripts, and so appears to work, but I get errors when linking because various epics 3 libraries are referred to as /epics/base-3.15.4 etc. and the linker appears to want a c:/epics/base-3.15... syntax.  My solution was to modify the epics base to use ../../../../ etc ... basically if you add a library in relative path syntax, the linker was happy. Otherwise, the absolute path needed to begin with a drive: for the linker to be happy.

So, eventually, I was able to get epics 4 to build but had to modify the EPICS_BASE environment variable every time a linker had an issue, and run make in that build folder only.  Then reset to the base directory and reset EPICS_BASE to make the perl script happy and proceed to the next build step.

My conclusion was that it's some sort of globbing problem, maybe my path is different, maybe my path is different, or I'm using a different linker, or the lib path needs to be enclosed in quotes,  or I'm not escaping the EPICS_BASE path correctly, or the perl script has some sort of bug based upon my paths or version of perl, etc. 

For the record, I'm using strawberry perl v5.24.0 and GNU Make 3.81

Let me know if I should try something else. 

Regards,

W. Todd Sneed
nHance Technologies
122 Cornerstone St.
Lynchburg, VA  24502
(work) (434) 582-6110,10
(iphone) (434) 444-5110
todd.sneed@nhancetech.com

**Comment by anjohnson** [comment]
Hi Todd,

On 08/18/2016 08:02 AM, W. Todd.Sneed wrote:

> For the record, I'm using strawberry perl v5.24.0 and GNU Make 3.81

Thanks for the detailed error report. Please try building using a newer
GNU Make as these kinds of problems were common with older versions on
Windows, but recent releases seem to have resolved those issues and Make
now fully understand C:/... paths. Strawberry Perl comes with its own
copy of GNU Make (they usually call it gmake.exe though) which has been
upgraded to Make 4.1 in Perl 5.24.0. You may be able to just try typing
'gmake' instead of 'make' with your existing configuration (after
undoing your modifications).

You can also try using the GNU Make 4.1 binary that I cross-built using
MinGW on Linux, a link to which is published under Other Build Tools on
http://www.aps.anl.gov/epics/base/win32.php — many other people have
used this successfully.

Let me know if either of these fix the issue (or not).
- Andrew

## 

Arguing for surveillance because you have nothing to hide is no
different than making the claim, "I don't care about freedom of
speech because I have nothing to say." -- Edward Snowdon

**Comment by anjohnson** [comment]
Andrew,

The wrong version of Make was the problem. (The version of strawberry I was using did not have gmake included, but I downloaded your binary and it worked).  I want to clean up and test a little more with different compilers but I'm good to go.  Thanks!

Regards,

W. Todd Sneed
nHance Technologies
122 Cornerstone St.
Lynchburg, VA  24502
(work) (434) 582-6110,10
(iphone) (434) 444-5110

**Comment by anjohnson** [comment]
Closing
