### ISSUE TITLE
Public URL in .gitmodules

### ISSUE THREAD

**Issue by donpatrice** [epics-base/bundleCPP#5]
Shouldn't the URLs in the .gitmodules be public instead of private?
For example:
url = https://github.com/epics-base/pvCommonCPP.git
instead of
url = git@github.com:epics-base/pvCommonCPP.git

**Comment by anjohnson** [comment]
The bundleCPP module was designed for the use by the core developers, who all have github accounts so can use the "private" URLs (i.e. over SSH instead of HTTPS).

If someone wants a copy of EPICS V4 we would much prefer that they download a released version tarfile than recursively clone this repository. Note that all the individual submodules are usually checked out at tagged release versions from their release branches, so the user would have to know git well enough to switch them to the tips of their master branches if they want to follow along with development. Not that there has been much if any coding in V4 since the last release anyway.

Does that answer the question?

**Comment by ralphlange** [comment]
Even being a core developer, my company firewall doesn't allow outgoing ssh, so these "private" URLs are for me just dysfunctional.

While all that Andrew writes is true, it is not an argument against https URLs that work for everybody.

**Comment by hjunkes** [comment]
"donpatrice" is the new mathematician working with me. He started 1st of January. He should deal with the archiverAppliance, pva2pva, ... ;-)

**Comment by ralphlange** [comment]
Oh, ah, just a sec...

**Comment by ralphlange** [comment]
Actually, I had never checked out that module, that's why I didn't "fix" these links earlier.

**Comment by ralphlange** [comment]
Should work now. (Does for me :-)

**Comment by donpatrice** [comment]
Thank you Ralph, it's also working for me. :-)
